#!/usr/bin/env python3

from argparse import ArgumentParser
import sys

def main(argv):
	parser = ArgumentParser()
	args = parser.parse_args(argv[1:])

	return 0

if __name__ == "__main__":
	sys.exit(main(sys.argv))
